data:
  categorical_features:
  - club_name
  - preferred_foot
  - work_rate
  features_path: ../data/processed/train_scaled.csv
  numeric_features:
  - age
  - height_cm
  - weight_kg
  - overall
  - potential
  - defending_sliding_tackle
  - movement_balance
  - mentality_positioning
  - defenging_marking_awareness
  prospect_max_age: 23
  prospect_threshold: 5
  random_state: 42
  target_classification: is_prospect
  target_regression: value_eur
  test_size: 0.2
modeling:
  classification_models:
  - random_forest
  - xgboost
  - lightgbm
  - catboost
  - logistic
  - stacking
  cv_folds: 5
  hyperparameters:
    random_forest:
      max_depth:
      - null
      - 10
      - 20
      min_samples_split:
      - 2
      - 5
      n_estimators:
      - 100
      - 200
    xgboost:
      learning_rate:
      - 0.01
      - 0.1
      max_depth:
      - 3
      - 6
      n_estimators:
      - 100
      - 200
  regression_models:
  - random_forest
  - xgboost
  - lightgbm
  - catboost
  - gradient_boosting
  - stacking
output:
  feature_importance_top_n: 15
  model_dir: ../models
